spring.datasource.url=jdbc:postgresql://dpg-d88m9lv7f7vs73bd378g-a:5432/portfolio_db_7cp2
spring.datasource.username=madhu
spring.datasource.password=QZ8RPsat1V8bJvtvg5uVDzNJgOIvIxIn 

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

