spring.datasource.url=jdbc:postgresql://dpg-d8arerel51nc73f6i1b0-a:5432/portfolio_cj6b
spring.datasource.username=portfolio_cj6b_user
spring.datasource.password=YOUR_NEW_PASSWORD

server.port=${PORT:8080}
server.address=0.0.0.0
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
